---
name: Create Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Create release from tag
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          generate_release_notes: true
